"""Check public notes against the note templates in docs/note-templates.md.

`load_notes` enforces the basic note contract (frontmatter, sources, EN/DE
sections). This module adds the template rules: required frontmatter per
template, the LLM notice, required sections in order, EN/DE parity, and that
every frontmatter source is cited in the text. It returns a list of problems
instead of raising, so that all problems of a note are reported at once.
"""

from __future__ import annotations

import datetime as dt
import re
from pathlib import Path

import yaml

from app.backend.knowledge_radar.notes import FRONTMATTER_PATTERN, SECTION_PATTERN

TEMPLATES = ("regulatory", "technical")

# (EN heading, DE heading); required sections must appear in this order.
REGULATORY_REQUIRED = [
    ("TL;DR", "TL;DR"),
    ("Key facts", "Eckdaten"),
    ("Scope", "Anwendungsbereich"),
    ("Timeline", "Zeitplan"),
    ("Enforcement and penalties", "Durchsetzung und Sanktionen"),
    ("Relationship to other acts", "Verhältnis zu anderen Rechtsakten"),
    ("Relevance for AI development", "Bedeutung für die KI-Entwicklung"),
    ("Official sources", "Amtliche Quellen"),
]
TECHNICAL_REQUIRED = [
    ("TL;DR", "TL;DR"),
    ("How it works", "Funktionsweise"),
    ("When to use it", "Wann einsetzen"),
    ("Strengths and limitations", "Stärken und Grenzen"),
    ("Comparison", "Vergleich"),
    ("Key takeaway", "Merksatz"),
    ("Sources", "Quellen"),
]
TECHNICAL_OPTIONAL = [
    ("In practice", "In der Praxis"),
    ("Regulatory context", "Regulatorischer Kontext"),
]
# Dated update entries (note_updates.py); always the last section.
UPDATES = ("Updates", "Aktualisierungen")
# Technology notes replace "How it works" with these two sections.
TECHNOLOGY_MECHANISM = [("Core concepts", "Kernkonzepte"), ("Common usage", "Typische Verwendung")]

FORBIDDEN_HEADINGS = {
    "Contents", "Table of contents", "Inhalt", "Inhaltsverzeichnis",
    "Related topics", "See also", "Verwandte Themen", "Siehe auch",
}
NOTICES = {
    "EN": ("> **Note:**", "> **Important notice:**"),
    "DE": ("> **Hinweis:**", "> **Wichtiger Hinweis:**"),
}
REGULATION_FIELDS = {
    "jurisdiction": {"EU", "DE", "International"},
    "instrument": {"regulation", "directive", "national-law", "guideline", "standard"},
    "status": {"proposed", "adopted", "in-force", "partially-applicable", "repealed"},
}
HEADING = re.compile(r"^(#{3,4})\s+(.+?)\s*$")
URL = re.compile(r"https?://[^\s)>\]]+")


def default_template(entity_type: str) -> str:
    return "regulatory" if entity_type == "Regulation" else "technical"


def _headings(markdown: str) -> list[tuple[int, str]]:
    found, in_fence = [], False
    for line in markdown.splitlines():
        if line.startswith(("```", "~~~")):
            in_fence = not in_fence
        match = not in_fence and HEADING.match(line)
        if match:
            found.append((len(match.group(1)), match.group(2)))
    return found


def _in_order(required: list[str], present: list[str]) -> bool:
    positions = [present.index(heading) for heading in required if heading in present]
    return positions == sorted(positions)


def _check_frontmatter(frontmatter: dict, template: str) -> list[str]:
    problems = []
    entity_type = frontmatter.get("entity_type")
    if template == "regulatory" and entity_type == "Regulation":
        for field, allowed in REGULATION_FIELDS.items():
            if frontmatter.get(field) not in allowed:
                problems.append(f"'{field}' must be one of {sorted(allowed)}.")
        if not isinstance(frontmatter.get("official_reference"), str):
            problems.append("'official_reference' is required (e.g. \"Regulation (EU) 2024/1689\").")
        if not isinstance(frontmatter.get("consolidated_version"), dt.date):
            problems.append("'consolidated_version' must be a date (YYYY-MM-DD).")
    elif template == "regulatory":
        if frontmatter.get("jurisdiction") not in REGULATION_FIELDS["jurisdiction"]:
            problems.append(f"'jurisdiction' must be one of {sorted(REGULATION_FIELDS['jurisdiction'])}.")
    return problems


def _check_language(text: str, lang: str, template: str, entity_type: str) -> list[str]:
    problems = []
    if not text.lstrip().startswith(NOTICES[lang]):
        problems.append(f"{lang}: must open with the LLM notice ({' or '.join(NOTICES[lang])}).")

    headings = _headings(text)
    top = [title for level, title in headings if level == 3]
    index = 0 if lang == "EN" else 1
    if not top or top[0] != "TL;DR":
        problems.append(f"{lang}: the first section must be '### TL;DR'.")
    for title in top:
        if title in FORBIDDEN_HEADINGS:
            problems.append(f"{lang}: remove '### {title}' (generated by the site / replaced by inline links).")

    if template == "regulatory":
        required = [pair[index] for pair in REGULATORY_REQUIRED]
        allowed = None  # chapters, recitals and annexes are free-form
    else:
        pairs = TECHNICAL_REQUIRED
        if entity_type == "Technology":
            how = TECHNICAL_REQUIRED.index(("How it works", "Funktionsweise"))
            pairs = pairs[:how] + TECHNOLOGY_MECHANISM + pairs[how + 1:]
        required = [pair[index] for pair in pairs]
        allowed = set(required) | {pair[index] for pair in TECHNICAL_OPTIONAL} | {UPDATES[index]}

    if UPDATES[index] in top and top[-1] != UPDATES[index]:
        problems.append(f"{lang}: '### {UPDATES[index]}' must be the last section.")

    missing = [title for title in required if title not in top]
    if missing:
        problems.append(f"{lang}: missing sections: {', '.join(missing)}.")
    elif not _in_order(required, top):
        problems.append(f"{lang}: sections must follow the order {' > '.join(required)}.")
    if allowed is not None:
        unexpected = [title for title in top if title not in allowed]
        if unexpected:
            problems.append(f"{lang}: sections not in the technical template: {', '.join(unexpected)}.")
    return problems


def check_language_part(text: str, lang: str, template: str, entity_type: str) -> list[str]:
    """Template problems of one language part ("EN"/"DE") on its own, e.g. for a draft."""
    return _check_language(text, lang, template, entity_type)


def check_template(text: str) -> list[str]:
    """Return all template problems of one note's file content (empty if it conforms)."""
    match = FRONTMATTER_PATTERN.match(text)
    if match is None:
        return ["YAML frontmatter is required."]
    frontmatter = yaml.safe_load(match.group(1)) or {}
    body = text[match.end():]

    entity_type = str(frontmatter.get("entity_type", ""))
    template = frontmatter.get("template", default_template(entity_type))
    if template not in TEMPLATES:
        return [f"'template' must be one of {list(TEMPLATES)}."]

    problems = _check_frontmatter(frontmatter, template)

    headers = list(SECTION_PATTERN.finditer(body))
    sections = {}
    for position, header in enumerate(headers):
        end = headers[position + 1].start() if position + 1 < len(headers) else len(body)
        sections[header.group(1)] = body[header.end():end]
    for lang in ("EN", "DE"):
        problems += _check_language(sections.get(lang, ""), lang, template, entity_type)

    en_outline = [level for level, _ in _headings(sections.get("EN", ""))]
    de_outline = [level for level, _ in _headings(sections.get("DE", ""))]
    if en_outline != de_outline:
        problems.append(
            f"EN and DE must have the same outline: EN has {en_outline.count(3)} '###' and "
            f"{en_outline.count(4)} '####' headings, DE has {de_outline.count(3)} and {de_outline.count(4)}."
        )

    cited = set(URL.findall(body))
    for source in frontmatter.get("sources") or []:
        if isinstance(source, str) and source.strip() not in cited:
            problems.append(f"source not cited in the text: {source}")
    return problems


def check_template_file(path: Path) -> list[str]:
    return check_template(path.read_text(encoding="utf-8"))
