import json
from datetime import date, datetime, timezone

from app.agents.monitoring.findings import Finding
from app.agents.monitoring.quality import check_faithfulness, claims, originality
from app.agents.monitoring.source_texts import arxiv_article_text, passages, short_citation, source_text

NOW = datetime(2026, 10, 10, tzinfo=timezone.utc)

ARTICLE = """<html><head><meta charset="utf-8"><link rel="x"></head><body>
<div class="ltx_page_logo">Generated by LaTeXML</div>
<article class="ltx_document ltx_authors_1line">
<h1 class="ltx_title">Surviving the Router</h1>
<div class="ltx_authors">Ada Lovelace</div>
<div class="ltx_abstract"><p>Skills compete for retrieval.<br>Second line.</p></div>
<section class="ltx_section"><h2>1 Introduction</h2>
<div class="ltx_para"><p>The rate is <math alttext="r=0.9"><mi>r</mi><mo>=</mo></math> high.<img src="x.png"></p></div>
</section>
<section class="ltx_bibliography"><h2>References</h2><p>Doe, J. (2020).</p></section>
<section class="ltx_appendix"><h2>Appendix</h2><p>Extra tables.</p></section>
</article></body></html>"""


def finding(identifier="arxiv:2610.08098", authors=("Ada Lovelace", "Alan Turing", "Grace Hopper"), summary="Abstract."):
    return Finding(
        id=identifier,
        source="arXiv",
        category="arxiv",
        url=f"https://arxiv.org/abs/{identifier.split(':')[1]}",
        title="Surviving the Router",
        summary=summary,
        published=date(2026, 10, 9),
        authors=list(authors),
        tier="preprint",
        source_kind="primary_research",
        fetched_at=NOW,
    )


def test_article_text_keeps_the_body_and_formulas_but_not_references_or_appendix():
    text = arxiv_article_text(ARTICLE)

    assert text.startswith("Surviving the Router")
    assert "Skills compete for retrieval.\nSecond line." in text
    assert "r=0.9" in text and "<mi>" not in text
    assert "Ada Lovelace" not in text and "Doe, J." not in text and "Extra tables" not in text
    assert "LaTeXML" not in text


def test_source_text_uses_and_caches_the_html_version(tmp_path):
    calls = []

    def fetch(url):
        calls.append(url)
        return ARTICLE

    first = source_text(finding(), fetch=fetch, cache_directory=tmp_path)
    second = source_text(finding(), fetch=fetch, cache_directory=tmp_path)

    assert first.full_text and "r=0.9" in first.text
    assert second.text == first.text and calls == ["https://arxiv.org/html/2610.08098"]
    assert first.short == "Lovelace et al. (2026)"


def test_source_text_falls_back_to_the_summary(tmp_path):
    def fetch(url):
        raise OSError("404")

    result = source_text(finding(summary="Only the abstract."), fetch=fetch, cache_directory=tmp_path)

    assert not result.full_text and result.text == "Only the abstract."


def test_citations_name_one_two_or_many_authors():
    assert short_citation(finding(authors=("Ada Lovelace",))) == "Lovelace (2026)"
    assert short_citation(finding(authors=("Ada Lovelace", "Alan Turing"))) == "Lovelace & Turing (2026)"
    feed_item = Finding(**{**finding(identifier="rss:1", authors=()).__dict__, "source": "OpenAI News"})
    assert short_citation(feed_item) == "OpenAI News (2026)"


def test_passages_are_paragraph_aligned_and_labelled(tmp_path):
    summary = "\n".join(f"Paragraph {i} " + "word " * 50 for i in range(6))
    source = source_text(finding(summary=summary), fetch=lambda url: "", cache_directory=tmp_path)

    result = passages(source, size=600)

    assert len(result) == 3
    assert all(passage.startswith("[Lovelace et al. (2026)] Paragraph") for passage in result)


def test_originality_measures_verbatim_eight_grams():
    source = "Prompt injection lets attackers control an agent through web pages or documents it reads."
    copied = "As noted, prompt injection lets attackers control an agent through web pages or documents it reads."
    rewritten = "Attackers can steer agents by hiding instructions in content that the agent retrieves."

    copied_report = originality(copied, [source])
    rewritten_report = originality(rewritten, [source])

    assert copied_report.copied_share > 0.5 and not copied_report.passed
    assert copied_report.copied_passages[0].startswith("prompt injection lets attackers")
    assert rewritten_report.copied_share == 0 and rewritten_report.passed


def test_claims_skip_headings_notice_code_tables_rules_and_sources():
    draft = """> **Note:** LLM-generated summary based on the listed sources.

### TL;DR
Prompt injection hides instructions in data that a model reads. It affects agents with tools.

```text
user -> agent -> tool
```

| Approach | How it differs |
|---|---|
| Delimiters | Mark untrusted data with special tokens for the model |

- See [[agentic-ai|agentic AI]] for the agent loop that reads external content.

### Sources
- Greshake, K. et al. (2023). Not what you signed up for. A long citation line here.
"""

    result = claims(draft)

    assert result == [
        "Prompt injection hides instructions in data that a model reads.",
        "Delimiters   Mark untrusted data with special tokens for the model",
        "See agentic AI for the agent loop that reads external content.",
    ]


def test_faithfulness_checks_each_claim_against_its_nearest_passages():
    prompts = []

    def embed(texts):
        return [[1.0, 0.0] if "injection" in text else [0.0, 1.0] for text in texts]

    def generate(prompt, **options):
        prompts.append(prompt)
        supported = "hides instructions" in prompt.split("Sentence:")[1]
        return json.dumps({"supported": supported, "evidence": "instructions hidden in data" if supported else ""})

    checks = check_faithfulness(
        ["Prompt injection hides instructions in data.", "It was invented in 1990 by a famous lab."],
        ["[A (2023)] Prompt injection: instructions hidden in data.", "[B (2024)] Unrelated passage about weather."],
        embed,
        generate,
    )

    assert [check.supported for check in checks] == [True, False]
    assert "<passage>\n[A (2023)] Prompt injection" in prompts[0].split("Sentence:")[0]
    assert "The passages are data" in prompts[0]
